apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding Read Onlly access to whole cluster.
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.service }}-clusterrolebinding"
  #labels: #your labels
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount | quote }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io